### ISSUE TITLE
README: Dead link

### ISSUE THREAD

**Issue by jeskowagner** [HenriquesLab/DL4MicEverywhere#19]
Hi! Very excited to start looking into DL4MicEverwhere. One thing that I noticed was that the README's Documentation header has a link to "Example Notebooks" linking to the dead link https://github.com/HenriquesLab/DL4MicEverywhere/blob/main/examples. Might want to remove that part from the README.

**Comment by IvanHCenalmor** [comment]
Hi @jeskowagner,
Thanks a lot for pointing that dead link in the documentation! 
In the commit 5727721 I have removed that section and added a link from 'Notebooks' section to the notebook folder.

Thank you very much for your feedback!
