### ISSUE TITLE
Request argument to choose Port when running remotely

### ISSUE THREAD

**Issue by nunopimpaomartins** [HenriquesLab/DL4MicEverywhere#51]
**Is your feature request related to a problem? Please describe.**
No. I would like to specify a port when running DL4MicEverywhere so that it does not use the default port.

**Describe the solution you'd like**
Allow to specify a port for forwarding when running DL4MicEverywhere remotely with a `--port` flag or argument.

**Comment by IvanHCenalmor** [comment]
Hi @nunopimpaomartins,

I’ve added the requested feature in commit 65fb2e53f8ac32cc1145036461686c27359e75f0.

When using the command line, the port number can now be forwarded with the `-p` argument. The program will still check if that port is available, and if it’s not, it will incrementally try the next port until it finds an available one. However, if the user specifies a port, we assume that it is available and will open on the selected port.

Thanks a lot for the feedback and contribution! 🤗
